# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

executors:
  node:
    docker:
      - image: circleci/node:8

aliases:
  install_node_modules: &install_node_modules
    run:
      name: Install dependencies
      command: yarn

version: 2.1

jobs:
  test:
    executor: node
    steps:
      - checkout
      - <<: *install_node_modules
      - run:
          name: Test
          command: yarn test-ci
      - store_test_results:
          path: test-results

  build:
    executor: node
    steps:
      - checkout
      - <<: *install_node_modules
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: ./
          paths:
            - dist

  deploy:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - <<: *install_node_modules
      - run:
          name: Install netlify-cli
          command: sudo npm install -g --silent netlify-cli
      - run:
          name: Deploy to Netlify
          command: netlify deploy --dir=./dist -p

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
