on: pull_request
name: Pull Request
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
